### ISSUE TITLE
install problem with current trunk

### ISSUE THREAD

**Issue by ycollet** [moddevices/mda-lv2#2]
./waf install fails with the following error message:

Waf: Leaving directory `/home/collette/repositories/LV2/portalmod/mda-lv2/build'
Build failed
Traceback (most recent call last):
  File "/home/collette/repositories/LV2/portalmod/mda-lv2/.waf-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Task.py", line 123, in process
    ret=self.run()
  File "/home/collette/repositories/LV2/portalmod/mda-lv2/.waf-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Task.py", line 47, in run
    return m1(self)
  File "/home/collette/repositories/LV2/portalmod/mda-lv2/.waf-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Build.py", line 460, in run
    return self.generator.exec_task()
  File "/home/collette/repositories/LV2/portalmod/mda-lv2/.waf-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Build.py", line 476, in exec_install_files
    self.generator.bld.do_install(y.abspath(),destfile,self.chmod)
  File "/home/collette/repositories/LV2/portalmod/mda-lv2/.waf-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Build.py", line 517, in do_install
    shutil.copy2(src,tgt)
  File "/usr/lib64/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 98, in copystat
    os.utime(dst, (st.st_atime, st.st_mtime))
OSError: [Errno 2] No such file or directory: '/local/stow/mda-lv2-devel/lib/lv2/mod-mda-BeatBox.lv2/modgui/knobs/boxy/black.png'

**Comment by falkTX** [comment]
you need to use "-j1" during install.

**Comment by ycollet** [comment]
Thanks a lot.

YC

**Comment by falkTX** [comment]
Now fixed by removing the custom modguis, which are stored elsewhere
