### ISSUE TITLE
Build issue on current master

### ISSUE THREAD

**Issue by JohannesLorenz** [moddevices/mda-lv2#4]
Can someone please help me with this `waf configure` issue?

```
$ ./waf configure
Traceback (most recent call last):
  File "/home/johannes/cprogs/mda-lv2/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Node.py", line 282, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/johannes/cprogs/mda-lv2/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Scripting.py", line 97, in waf_entry_point
    run_commands()
  File "/home/johannes/cprogs/mda-lv2/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Scripting.py", line 149, in run_commands
    parse_options()
  File "/home/johannes/cprogs/mda-lv2/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Scripting.py", line 127, in parse_options
    Context.create_context('options').execute()
  File "/home/johannes/cprogs/mda-lv2/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Options.py", line 134, in execute
    super(OptionsContext,self).execute()
  File "/home/johannes/cprogs/mda-lv2/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Context.py", line 87, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/johannes/cprogs/mda-lv2/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Context.py", line 128, in recurse
    user_function(self)
  File "/home/johannes/cprogs/mda-lv2/wscript", line 16, in options
    opt.load('compiler_cxx')
  File "/home/johannes/cprogs/mda-lv2/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Context.py", line 84, in load
    fun(self)
  File "/home/johannes/cprogs/mda-lv2/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Tools/compiler_cxx.py", line 31, in options
    opt.load_special_tools('cxx_*.py')
  File "/home/johannes/cprogs/mda-lv2/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Context.py", line 264, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/home/johannes/cprogs/mda-lv2/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Node.py", line 331, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=25,dir=dir,src=src,remove=kw.get('remove',True))]
  File "/home/johannes/cprogs/mda-lv2/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Node.py", line 331, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=25,dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration
```

**Comment by JohannesLorenz** [comment]
note: it works on https://gitlab.com/drobilla/mda-lv2

**Comment by falkTX** [comment]
waf needs to be updated.
should be just a matter of grabbing the latest binary release and placing it here.
PRs welcome

**Comment by JohannesLorenz** [comment]
FYI: works on [drobilla's "fork"](https://gitlab.com/drobilla/mda-lv2).

**Comment by phil123456** [comment]
cant clone the repository
